src/Entity/Account.php
<?php


namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="account")
 * @ORM\Entity()
 */
class Account
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_created;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_confirmed;

    /**
     * @ORM\Column(type="string")
     */
    private $first_name;

    /**
     * @ORM\Column(type="string")
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $postcode;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_of_birth;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $phone_number;

    /**
     * @ORM\OneToOne(targetEntity="User")
     */
    private $user;

    /**
     * @ORM\OneToOne(targetEntity="Profile")
     */
    private $profile;

    /**
     * @ORM\OneToMany(targetEntity="Order", mappedBy="account")
     */
    private $orders;

    /**
     * @ORM\OneToOne(targetEntity="Genblueprint")
     */
    private $genblueprint;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $free;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $agree;

    public function __construct(){
        $this->date_created = new \DateTime();
    }

    /**
     * $param array $values
     */
    public function edit($values)
    {
        if (isset($values['first_name'])) {
            $this->setFirstName($values['first_name']);
        }
        if (isset($values['last_name'])) {
            $this->setLastName($values['last_name']);
        }
        if (isset($values['address'])) {
            $this->setAddress($values['address']);
        }
        if (isset($values['postcode'])) {
            $this->setPostcode($values['postcode']);
        }
        if (isset($values['city'])) {
            $this->setCity($values['city']);
        }
        if (isset($values['date_of_birth'])) {
            $this->setDateOfBirth(new \DateTime($values['date_of_birth']));
        }
        if (isset($values['phone_number'])) {
            $this->setPhoneNumber($values['phone_number']);
        }
        if (isset($values['agree'])) {
            $this->setAgree($values['agree']);
        }
    }

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function getDateCreated()
    {
        if (!is_null($this->date_created)) {
            return $this->date_created->format('Y-m-d H:i:s');
        }
        return $this->date_created;
    }

    public function setDateCreated($date_created)
    {
        $this->date_created = $date_created;
    }

    public function getDateConfirmed()
    {
        if (!is_null($this->date_confirmed)) {
            return $this->date_confirmed->format('Y-m-d H:i:s');
        }
        return $this->date_confirmed;
    }

    public function setDateConfirmed($date_confirmed)
    {
        $this->date_confirmed = $date_confirmed;
    }

    public function getFirstName()
    {
        return $this->first_name;
    }

    public function setFirstName($first_name)
    {
        $this->first_name = $first_name;
    }

    public function getLastName()
    {
        return $this->last_name;
    }

    public function setLastName($last_name)
    {
        $this->last_name = $last_name;
    }

    public function getDateOfBirth()
    {
        if (!is_null($this->date_of_birth)) {
            return $this->date_of_birth->format('Y-m-d');
        }
        return $this->date_of_birth;
    }

    public function setDateOfBirth($date_of_birth)
    {
        $this->date_of_birth = $date_of_birth;
    }

    public function getPhoneNumber()
    {
        return $this->phone_number;
    }

    public function setPhoneNumber($phone_number)
    {
        $this->phone_number = $phone_number;
    }

    public function getFullName()
    {
        $full_name = $this->getFirstName();
        $full_name .= " " . $this->getLastName();
        return $full_name;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function setUser(User $user)
    {
        $this->user = $user;
    }

    public function getProfile()
    {
        return $this->profile;
    }

    public function setProfile($profile)
    {
        $this->profile = $profile;
    }

    public function getAddress()
    {
        return $this->address;
    }

    public function setAddress($address)
    {
        $this->address = $address;
    }

    public function getPostcode()
    {
        return $this->postcode;
    }

    public function setPostcode($postcode)
    {
        $this->postcode = $postcode;
    }

    public function getCity()
    {
        return $this->city;
    }

    public function setCity($city)
    {
        $this->city = $city;
    }

    public function getOrders()
    {
        return $this->orders;
    }

    public function setOrders($orders)
    {
        $this->orders = $orders;
    }

    public function getGenblueprint()
    {
        return $this->genblueprint;
    }

    public function setGenblueprint($genblueprint)
    {
        $this->genblueprint = $genblueprint;
    }

    public function getFree()
    {
        return $this->free;
    }

    public function setFree($free)
    {
        $this->free = $free;
    }

    public function toggleFree()
    {
        $this->free = $this->free ? false : true;
    }

    public function getAgree()
    {
        return $this->agree;
    }

    public function setAgree($agree): void
    {
        $this->agree = $agree;
    }
}

src/Entity/Order.php
<?php


namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 * @ORM\Table(name="orders")
 */
class Order
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Account", inversedBy="orders")
     */
    private $account;

    /**
     * @ORM\OneToMany(targetEntity="OrderLine", mappedBy="order")
     */
    private $orderLines;

    /**
     * @ORM\Column(type="string")
     */
    private $status = 'open';

    /**
     * @ORM\Column(type="decimal", scale=2)
     */
    private $total_price;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $payment_method;

    /**
     * @ORM\Column(type="string", unique=true, nullable=true)
     */
    private $payment_provider_id = null;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_created;

    public function __construct()
    {
        $this->date_created = new \DateTime();
    }

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function getAccount()
    {
        return $this->account;
    }

    public function setAccount($account)
    {
        $this->account = $account;
    }

    public function getOrderLines()
    {
        return $this->orderLines;
    }

    public function setOrderLines($orderLines)
    {
        $this->orderLines = $orderLines;
    }

    public function getStatus()
    {
        return $this->status;
    }

    public function setStatus($status)
    {
        $this->status = $status;
    }

    public function getTotalPrice()
    {
        return $this->total_price;
    }

    public function setTotalPrice($price)
    {
        $this->total_price = $price;
    }

    public function getPaymentMethod()
    {
        return $this->payment_method;
    }

    public function setPaymentMethod($payment_method)
    {
        $this->payment_method = $payment_method;
    }

    public function getPaymentProviderId()
    {
        return $this->payment_provider_id;
    }

    public function setPaymentProviderId($payment_provider_id)
    {
        $this->payment_provider_id = $payment_provider_id;
    }

    public function getDateCreated()
    {
        if (!is_null($this->date_created)) {
            return $this->date_created->format('Y-m-d H:i:s');
        }
        return $this->date_created;
    }

    public function setDateCreated($date_created)
    {
        $this->date_created = $date_created;
    }
}

src/Entity/Product.php
<?php


namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class Product
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="decimal", scale=2)
     */
    private $price;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $ebook;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $video;

    /**
     * @ORM\Column(type="boolean")
     */
    private $has_genblueprint = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_clothing = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $deleted = false;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription($description)
    {
        $this->description = $description;
    }

    public function getPrice()
    {
        return $this->price;
    }

    public function setPrice($price)
    {
        $this->price = $price;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;
    }

    public function getEbook()
    {
        return $this->ebook;
    }

    public function setEbook($ebook)
    {
        $this->ebook = $ebook;
    }

    public function getVideo()
    {
        return $this->video;
    }

    public function setVideo($video)
    {
        $this->video = $video;
    }

    public function getHasGenblueprint()
    {
        return $this->has_genblueprint;
    }

    public function setHasGenblueprint($has_genblueprint)
    {
        $this->has_genblueprint = $has_genblueprint;
    }

    public function getIsClothing()
    {
        return $this->is_clothing;
    }

    public function setIsClothing($is_clothing)
    {
        $this->is_clothing = $is_clothing;
    }

    public function getDeleted()
    {
        return $this->deleted;
    }

    public function setDeleted($deleted)
    {
        $this->deleted = $deleted;
    }

    public function delete()
    {
        $this->deleted = true;
    }
}

src/Controller/Account/AccountController.php
<?php


namespace App\Controller\Account;


use App\Controller\BaseController;
use App\Entity\Account;
use App\Service\GenBluePrintService;
use App\Service\Localization;

class AccountController extends BaseController
{
    public function account(Localization $localization)
    {
        if ($this->get('security.authorization_checker')->isGranted('ROLE_ADMIN')) {
            return $localization->redirectToLocalizedRoute('admin_dashboard');
        }

        $account = $this->getDoctrine()->getRepository(Account::class)->findOneBy(['user' => $this->getUser()->getId()]);

        return $this->render('website/account/account.twig', [
            'account' => $account,
            'hasGenBluePrintAccess' => GenBluePrintService::hasGenBluePrintAccess($account),
        ]);
    }
}

src/Controller/Account/AccountOverviewController.php
<?php


namespace App\Controller\Account;


use App\Controller\BaseController;
use App\Entity\Account;

class AccountOverviewController extends BaseController
{
    public function overview()
    {
        $accounts = $this->getDoctrine()->getRepository(Account::class)->findAll();

        $now = new \DateTime();
        foreach ($accounts as &$account) {
            $dob = new \DateTime($account->getDateOfBirth());
            $diff = $now->diff($dob);
            $account->age = $diff->y;
        }
        unset($account);

        return $this->render(
            'admin/account/account-overview.twig',
            [
                'accounts' => $accounts,
            ]
        );
    }
}

src/Controller/Account/AccountViewController.php
<?php


namespace App\Controller\Account;


use App\Controller\BaseController;
use App\Entity\Account;
use App\Entity\Genblueprint;
use App\Service\Localization;

class AccountViewController extends BaseController
{
    public function view($id)
    {
        $account = $this->getDoctrine()->getRepository(Account::class)->find($id);

        $now = new \DateTime();
        $dob = new \DateTime($account->getDateOfBirth());
        $diff = $now->diff($dob);
        $account->age = $diff->y;

        $genblueprint = [];
        if (!empty($account->getGenblueprint())) {
            $genblueprint = $this->calculateGenblueprint($account->getGenblueprint());
        }

        return $this->render(
            'admin/account/account-view.twig',
            [
                'a' => $account,
                'genblueprint' => $genblueprint,
            ]
        );
    }

    private function calculateGenblueprint(Genblueprint $genblueprint)
    {
        if (empty($genblueprint)) {
            return [];
        }

        $totals = [
            'green' => 0,
            'blue' => 0,
            'red' => 0,
            'total' => 0,
        ];
        foreach ($genblueprint->getAnswers() as $answer) {

            if (in_array($answer->getQuestion(), ['question01', 'question02', 'question03', 'question04', 'question05', 'question06'])) {
                continue;
            }

            if ($answer->getGreen()) {
                $totals['green']++;
                $totals['total']++;
            }
            if ($answer->getBlue()) {
                $totals['blue']++;
                $totals['total']++;
            }
            if ($answer->getRed()) {
                $totals['red']++;
                $totals['total']++;
            }
        }

        return [
            'green' => round(($totals['green'] / $totals['total']) * 100, 0),
            'blue' => round(($totals['blue'] / $totals['total']) * 100, 0),
            'red' => round(($totals['red'] / $totals['total']) * 100, 0),
        ];
    }

    public function toggleAccountFree($id, Localization $localization)
    {
        $account = $this->getDoctrine()->getRepository(Account::class)->find($id);
        $account->toggleFree();

        $free = $account->getFree() ? $localization->translate('Yes') : $localization->translate('No');

        $this->save($account);
        $this->addFlash('success', $localization->translate('Toggled free account to: ' . $free ));

        return $localization->redirectToLocalizedRoute('admin_account_view', ['id' => $id]);
    }

    public function toggleAccountActive($id, Localization $localization)
    {
        $account = $this->getDoctrine()->getRepository(Account::class)->find($id);
        $user = $account->getUser();
        $user->toggleActive();

        $active = $user->getIsActive() ? $localization->translate('Active') : $localization->translate('Inactive');

        $this->save($user);
        $this->addFlash('success', $localization->translate('Toggled account to: ' . $active ));

        return $localization->redirectToLocalizedRoute('admin_account_view', ['id' => $id]);
    }
}

templates/website/account/account.twig
{% extends 'website/base.html.twig' %}

{% block title %}{% trans %}Account{% endtrans %}{% endblock %}

{% block body %}
    <div class="page-content">
        <div class="account">
            <h1>{% trans %}Your account{% endtrans %}</h1>

            <div class="account-block">
                <a href="{{ getLocalizedRoute('account_complete_profile') }}">
                    <img src="{{ asset('img/complete_profile_' ~ app.request.getLocale() ~ '.png') }}">
                </a>
            </div>
            {% if hasGenBluePrintAccess %}
                {% set genblueprintUrl = getLocalizedRoute('account_genblueprint') %}
            {% else %}
                {% set genblueprintUrl = getLocalizedRoute('account_shop') %}
            {% endif %}
            <div class="account-block">
                <a href="{{ genblueprintUrl }}">
                    <img src="{{ asset('img/genblueprint_' ~ app.request.getLocale() ~ '.png') }}">
                </a>
            </div>
            <div class="account-block">
                <a href="{{ getLocalizedRoute('account_shop') }}">
                    <img src="{{ asset('img/shop_' ~ app.request.getLocale() ~ '.png') }}">
                </a>
            </div>
            <div class="account-block">
                <a href="{{ getLocalizedRoute('account_edit') }}">
                    <img src="{{ asset('img/edit_account_' ~ app.request.getLocale() ~ '.png') }}">
                </a>
            </div>
            <div class="account-block">
                <a href="{{ getLocalizedRoute('account_purchase_overview') }}">
                    <img src="{{ asset('img/purchases_' ~ app.request.getLocale() ~ '.png') }}">
                </a>
            </div>
            <div class="account-block">
                <a href="{{ getLocalizedRoute('logout') }}">
                    <img src="{{ asset('img/logout_' ~ app.request.getLocale() ~ '.png') }}">
                </a>
            </div>

            <div class="clear">&nbsp;</div>
        </div>
    </div>
{% endblock %}

templates/website/account/edit.twig
{% extends 'website/base.html.twig' %}

{% block title %}{% trans %}Edit account{% endtrans %}{% endblock %}

{% block body %}
    <div class="page-content">
        <div class="edit">
            <a href="{{ getLocalizedRoute('account') }}" class="button-small back-button">{% trans %}Back to account{% endtrans %}</a>
            <h1>{% trans %}Edit account{% endtrans %}</h1>

            {{ form_start(accountForm) }}

            <div class="form-field">
                {{ form_label(accountForm.first_name) }}
                {{ form_widget(accountForm.first_name, {value: account.firstName}) }}
            </div>

            <div class="form-field">
                {{ form_label(accountForm.last_name) }}
                {{ form_widget(accountForm.last_name, {value: account.lastName}) }}
            </div>

            <div class="form-field">
                {{ form_label(accountForm.address) }}
                {{ form_widget(accountForm.address, {value: account.address}) }}
            </div>

            <div class="form-field">
                {{ form_label(accountForm.postcode) }}
                {{ form_widget(accountForm.postcode, {value: account.postcode}) }}
            </div>

            <div class="form-field">
                {{ form_label(accountForm.city) }}
                {{ form_widget(accountForm.city, {value: account.city}) }}
            </div>

            <div class="form-field date-field">
                {{ form_label(accountForm.date_of_birth) }}
                {{ form_widget(accountForm.date_of_birth, {value: account.dateOfBirth}) }}
            </div>

            <div class="form-field">
                {{ form_label(accountForm.phone_number) }}
                {{ form_widget(accountForm.phone_number, {value: account.phoneNumber}) }}
            </div>

            <div class="clear">&nbsp;</div>

            <button type="submit" class="button-large">{% trans %}Edit{% endtrans %}</button>

            {{ form_end(accountForm) }}
        </div>
    </div>
{% endblock %}

templates/website/account/purchase-overview.twig
{% extends 'website/base.html.twig' %}

{% block title %}{% trans %}Purchases{% endtrans %}{% endblock %}

{% block body %}
    <div class="account-content">
        <div class="purchases">
            <a href="{{ getLocalizedRoute('account') }}" class="button-small back-button">{% trans %}Back to account{% endtrans %}</a>
            <h1>{% trans %}Purchase overview{% endtrans %}</h1>
            <div class="orders">
                {% for order in orders %}
                    <div class="order">
                        <div class="info">
                            <table>
                                <tr>
                                    <td>ID:</td><td>{{ order.id }}</td>
                                </tr>
                                <tr>
                                    <td>{% trans %}Order date{% endtrans %}:</td><td>{{ order.dateCreated|date("j F Y") }}</td>
                                </tr>
                                <tr>
                                    <td>{% trans %}Price{% endtrans %}:</td><td>&euro;{{ order.totalPrice|number_format(2) }}</td>
                                </tr>
                                <tr>
                                    <td>{% trans %}Payment method{% endtrans %}:</td><td>{{ order.paymentMethod }}</td>
                                </tr>
                                <tr>
                                    <td>{% trans %}Status{% endtrans %}:</td><td>{{ order.status }}</td>
                                </tr>
                            </table>
                        </div>
                        <div class="lines">
                            {% for line in order.orderLines %}
                                <div class="line">
                                    {% if line.product.ebook and order.status == 'paid' %}
                                        <a href="{{ getLocalizedRoute('account_download_purchase', {id: line.id}) }}" target="_blank" class="product-link">{{ line.product.title }}</a>
                                    {% elseif line.product.hasGenblueprint and order.status == 'paid' %}
                                        <a href="{{ getLocalizedRoute('account_genblueprint') }}" target="_blank" class="product-link">{{ line.product.title }}</a>
                                    {% else %}
                                        {{ line.product.title }}
                                    {% endif %}
                                    x{{ line.amount }}
                                    <span class="break"><br></span>
                                    {% if line.color %} | {{ line.color|capitalize }}{% endif %}
                                    {% if line.size %} | {{ line.size|capitalize }}{% endif %}
                                    <span class="right">&euro;{{ line.price|number_format(2) }}</span>
                                    <div class="clear"></div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/website/account/register.twig
{% extends 'website/base.html.twig' %}
{% form_theme accountForm 'website/form/fields.twig' %}
{% block title %}{% trans %}Register{% endtrans %}{% endblock %}

{% block body %}
    <div class="page-content">
        <div class="register">
            <h1>{% trans %}Register{% endtrans %}</h1>

            {{ form_start(userForm) }}

            <div class="form-field">
                {{ form_label(userForm.email) }}
                {{ form_widget(userForm.email) }}
                <input type="text" class="emailtest" name="emailtest" value="">
            </div>

            <div class="form-field">
                {{ form_label(userForm.plainPassword.first) }}
                {{ form_widget(userForm.plainPassword.first) }}
            </div>

            <div class="form-field">
                {{ form_label(userForm.plainPassword.second) }}
                {{ form_widget(userForm.plainPassword.second) }}
            </div>

            <div class="form-field">
                {{ form_label(accountForm.first_name) }}
                {{ form_widget(accountForm.first_name) }}
            </div>

            <div class="form-field">
                {{ form_label(accountForm.last_name) }}
                {{ form_widget(accountForm.last_name) }}
            </div>

            <div class="form-field">
                {{ form_label(accountForm.address) }}
                {{ form_widget(accountForm.address) }}
            </div>

            <div class="form-field">
                {{ form_label(accountForm.postcode) }}
                {{ form_widget(accountForm.postcode) }}
            </div>

            <div class="form-field">
                {{ form_label(accountForm.city) }}
                {{ form_widget(accountForm.city) }}
            </div>

            <div class="form-field date-field">
                {{ form_label(accountForm.date_of_birth) }}
                {{ form_widget(accountForm.date_of_birth) }}
            </div>

            <div class="form-field">
                {{ form_label(accountForm.phone_number) }}
                {{ form_widget(accountForm.phone_number) }}
            </div>

            <div class="clear">&nbsp;</div>

            <div class="form-field full-width">
                {{ form_widget(accountForm.agree) }}
            </div>

            <div class="clear">&nbsp;</div>

            <button type="submit" class="button-large">{% trans %}Register{% endtrans %}</button>

            {{ form_widget(accountForm._token) }}

            {{ form_end(userForm) }}
        </div>
    </div>
{% endblock %}

templates/website/account/registered.twig
{% extends 'website/base.html.twig' %}

{% block title %}{% trans %}Registered{% endtrans %}{% endblock %}

{% block body %}
    <div class="page-content">
        <h1>{% trans %}Registered successfully{% endtrans %}</h1>
        <p>
            {% trans %}You can now login.{% endtrans %}
        </p>
    </div>
{% endblock %}