src/Entity/Page.php
<?php


namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class Page
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=10)
     */
    private $locale;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="boolean")
     */
    private $slide = false;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $slide_title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $slide_text;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $button_text;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $slide_image;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $header;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $footer;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $call_to_action;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $call_to_action_link;

    public function __construct($id, $locale) {
        $this->id = $id;
        $this->locale = $locale;
    }

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function getLocale()
    {
        return $this->locale;
    }

    public function setLocale($locale)
    {
        $this->locale = $locale;
    }

    public function getSlug()
    {
        return $this->slug;
    }

    public function setSlug($slug)
    {
        $this->slug = $slug;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;
    }

    public function getContent()
    {
        return $this->content;
    }

    public function setContent($content)
    {
        $this->content = $content;
    }

    public function getSlide()
    {
        return $this->slide;
    }

    public function setSlide($slide)
    {
        $this->slide = $slide;
    }

    public function getSlideTitle()
    {
        return $this->slide_title;
    }

    public function setSlideTitle($slide_title)
    {
        $this->slide_title = $slide_title;
    }

    public function getSlideText()
    {
        return $this->slide_text;
    }

    public function setSlideText($slide_text)
    {
        $this->slide_text = $slide_text;
    }

    public function getButtonText()
    {
        return $this->button_text;
    }

    public function setButtonText($button_text)
    {
        $this->button_text = $button_text;
    }

    public function getSlideImage()
    {
        return $this->slide_image;
    }

    public function setSlideImage($slide_image)
    {
        $this->slide_image = $slide_image;
    }

    public function getHeader()
    {
        return $this->header;
    }

    public function setHeader($header)
    {
        $this->header = $header;
    }

    public function getFooter()
    {
        return $this->footer;
    }

    public function setFooter($footer)
    {
        $this->footer = $footer;
    }

    public function getCallToAction()
    {
        return $this->call_to_action;
    }

    public function setCallToAction($call_to_action)
    {
        $this->call_to_action = $call_to_action;
    }

    public function getCallToActionLink()
    {
        return $this->call_to_action_link;
    }

    public function setCallToActionLink($call_to_action_link)
    {
        $this->call_to_action_link = $call_to_action_link;
    }

    public function edit($values)
    {
        if (isset($values['content'])) {
            $this->setContent($values['content']);
        }
        if (isset($values['slug'])) {
            $this->setSlug($values['slug']);
        }
        if (isset($values['title'])) {
            $this->setTitle($values['title']);
        }
        if (isset($values['slide'])) {
            $this->setSlide($values['slide']);
        }
        if (isset($values['slide_title'])) {
            $this->setSlideTitle($values['slide_title']);
        }
        if (isset($values['slide_text'])) {
            $this->setSlideText($values['slide_text']);
        }
        if (isset($values['button_text'])) {
            $this->setButtonText($values['button_text']);
        }
        if (isset($values['slide_image'])) {
            $this->setSlideImage($values['slide_image']);
        }
        if (isset($values['header'])) {
            $this->setHeader($values['header']);
        }
        if (isset($values['footer'])) {
            $this->setFooter($values['footer']);
        }
        if (isset($values['call_to_action'])) {
            $this->setCallToAction($values['call_to_action']);
        }
        if (isset($values['call_to_action_link'])) {
            $this->setCallToActionLink($values['call_to_action_link']);
        }
    }
}

templates/website/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Neobodies{% endblock %}</title>

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('website/css/main.css') }}" />
    {% block stylesheets %}{% endblock %}
    <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}" />
</head>
<body>
    {% include 'website/main/navigation.twig' %}

    <div id="content">
        {% for label, messages in app.flashes %}
            {% for message in messages %}
                <div class="flash-message flash-{{ label }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endfor %}

        {% block body %}{% endblock %}
    </div>

    {% include 'website/main/footer.twig' %}
    {% block javascripts %}{% endblock %}
    <script type="text/javascript" src="{{ asset('website/js/navigation.js') }}"></script>
</body>
</html>

templates/website/contact.twig
{% extends 'website/base.html.twig' %}

{% block title %}{% trans %}Contact{% endtrans %}{% endblock %}

{% block body %}
    <div class='contact'>
        <div class="page-content">
            <h1>{% trans %}Leave us a message{% endtrans %}</h1>
            {{ form_start(form) }}
            <div class="contact-details">
                <div class="details-position">
                    {{ blocks.15.text|raw|nl2br }}
                </div>
            </div>
            <div class="sender-info">
                <div class="contact-field">
                    {{ form_label(form.name) }}
                    {{ form_widget(form.name) }}
                </div>

                <div class="contact-field">
                    {{ form_label(form.email) }}
                    {{ form_widget(form.email) }}
                    <input type="text" class="emailtest" name="emailtest" value="">
                </div>

                <div class="contact-field">
                    {{ form_label(form.phone) }}
                    {{ form_widget(form.phone) }}
                </div>
            </div>
            <div class="message">
                <div class="contact-field">
                    {{ form_label(form.message) }}
                    {{ form_widget(form.message) }}
                </div>

                <button type="submit" class="contact-button">{% trans %}Send{% endtrans %}</button>
            </div>

            {{ form_end(form) }}

            <div class="clear"></div>
        </div>
    </div>
{% endblock %}

templates/website/homepage.twig
{% extends 'website/base.html.twig' %}

{% block title %}Neobodies{% endblock %}

{% block body %}
    <div class="homepage-header-image" style="background-image: url('{% if blocks.1.image %}{{ asset('uploads/' ~ blocks.1.image) }}{% else %}{{ asset('img/top1.jpg') }}{% endif %}')">
        <div class="text-position">
            <div class="image-opacity-bar">
                <h1>{{ blocks.1.title }}</h1>
                <h2>{{ blocks.1.subtitle }}</h2>
            </div>
        </div>
    </div>

    <div class="usps">
        <div class="why">
            <h2>{{ blocks.2.title }}</h2>
        </div>
        <div class="usp-list">
            <div class="usp">
                <div class="image"><img src="{{ asset('uploads/' ~ blocks.3.image) }}"></div>
                <div class="text">
                    <h3>{{ blocks.3.title }}</h3>
                    <p>{{ blocks.3.subtitle }} </p>
                </div>
            </div>
            <div class="usp">
                <div class="image"><img src="{{ asset('uploads/' ~ blocks.4.image) }}"></div>
                <div class="text">
                    <h3>{{ blocks.4.title }}</h3>
                    <p>{{ blocks.4.subtitle }} </p>
                </div>
            </div>
            <div class="clear usp-mid-split">&nbsp;</div>
            <div class="usp">
                <div class="image"><img src="{{ asset('uploads/' ~ blocks.5.image) }}"></div>
                <div class="text">
                    <h3>{{ blocks.5.title }}</h3>
                    <p>{{ blocks.5.subtitle }} </p>
                </div>
            </div>
            <div class="usp">
                <div class="image"><img src="{{ asset('uploads/' ~ blocks.6.image) }}"> </div>
                <div class="text">
                    <h3>{{ blocks.6.title }}</h3>
                    <p>{{ blocks.6.subtitle }} </p>
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>

    {% if pages %}
        <div class="homepage-pages">
            <ul class="pages">
                {% for page in pages %}
                    <li>
                        <div class="image" style="background-image: url('{{ asset('uploads/' ~ page.slideImage) }}')">
                            <div class="image-text">
                                <div class="image-opacity-bar">
                                    <h2>{{ page.slideTitle }}</h2>
                                </div>
                            </div>
                        </div>
                        <div class="content">
                            <div class="content-position">
                                <div class="align-left">
                                    {{ page.slideText|raw }}
                                    <a href="{{ getLocalizedRoute('page_view', {slug: page.slug}) }}" class="button-large">{{ page.buttonText }}</a>
                                </div>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <div class="clear"></div>
        </div>
    {% endif %}

{% endblock %}