src/Entity/Page.php
<?php


namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class Page
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=10)
     */
    private $locale;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="boolean")
     */
    private $slide = false;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $slide_title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $slide_text;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $button_text;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $slide_image;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $header;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $footer;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $call_to_action;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $call_to_action_link;

    public function __construct($id, $locale) {
        $this->id = $id;
        $this->locale = $locale;
    }

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function getLocale()
    {
        return $this->locale;
    }

    public function setLocale($locale)
    {
        $this->locale = $locale;
    }

    public function getSlug()
    {
        return $this->slug;
    }

    public function setSlug($slug)
    {
        $this->slug = $slug;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;
    }

    public function getContent()
    {
        return $this->content;
    }

    public function setContent($content)
    {
        $this->content = $content;
    }

    public function getSlide()
    {
        return $this->slide;
    }

    public function setSlide($slide)
    {
        $this->slide = $slide;
    }

    public function getSlideTitle()
    {
        return $this->slide_title;
    }

    public function setSlideTitle($slide_title)
    {
        $this->slide_title = $slide_title;
    }

    public function getSlideText()
    {
        return $this->slide_text;
    }

    public function setSlideText($slide_text)
    {
        $this->slide_text = $slide_text;
    }

    public function getButtonText()
    {
        return $this->button_text;
    }

    public function setButtonText($button_text)
    {
        $this->button_text = $button_text;
    }

    public function getSlideImage()
    {
        return $this->slide_image;
    }

    public function setSlideImage($slide_image)
    {
        $this->slide_image = $slide_image;
    }

    public function getHeader()
    {
        return $this->header;
    }

    public function setHeader($header)
    {
        $this->header = $header;
    }

    public function getFooter()
    {
        return $this->footer;
    }

    public function setFooter($footer)
    {
        $this->footer = $footer;
    }

    public function getCallToAction()
    {
        return $this->call_to_action;
    }

    public function setCallToAction($call_to_action)
    {
        $this->call_to_action = $call_to_action;
    }

    public function getCallToActionLink()
    {
        return $this->call_to_action_link;
    }

    public function setCallToActionLink($call_to_action_link)
    {
        $this->call_to_action_link = $call_to_action_link;
    }

    public function edit($values)
    {
        if (isset($values['content'])) {
            $this->setContent($values['content']);
        }
        if (isset($values['slug'])) {
            $this->setSlug($values['slug']);
        }
        if (isset($values['title'])) {
            $this->setTitle($values['title']);
        }
        if (isset($values['slide'])) {
            $this->setSlide($values['slide']);
        }
        if (isset($values['slide_title'])) {
            $this->setSlideTitle($values['slide_title']);
        }
        if (isset($values['slide_text'])) {
            $this->setSlideText($values['slide_text']);
        }
        if (isset($values['button_text'])) {
            $this->setButtonText($values['button_text']);
        }
        if (isset($values['slide_image'])) {
            $this->setSlideImage($values['slide_image']);
        }
        if (isset($values['header'])) {
            $this->setHeader($values['header']);
        }
        if (isset($values['footer'])) {
            $this->setFooter($values['footer']);
        }
        if (isset($values['call_to_action'])) {
            $this->setCallToAction($values['call_to_action']);
        }
        if (isset($values['call_to_action_link'])) {
            $this->setCallToActionLink($values['call_to_action_link']);
        }
    }
}

src/Entity/Tool.php
<?php


namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class Tool
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=10)
     */
    private $locale;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $link;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $file;

    /**
     * @ORM\Column(type="boolean")
     */
    private $new_tab = false;


    public function __construct($locale)
    {
        $this->setLocale($locale);
    }

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function getLocale()
    {
        return $this->locale;
    }

    public function setLocale($locale)
    {
        $this->locale = $locale;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;
    }

    public function getContent()
    {
        return $this->content;
    }

    public function setContent($content)
    {
        $this->content = $content;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;
    }

    public function getLink()
    {
        return $this->link;
    }

    public function setLink($link)
    {
        $this->link = $link;
    }

    public function getFile()
    {
        return $this->file;
    }

    public function setFile($file)
    {
        $this->file = $file;
    }

    public function getNewTab()
    {
        return $this->new_tab;
    }

    public function setNewTab($new_tab)
    {
        $this->new_tab = $new_tab;
    }

    public function edit($values)
    {
        if (isset($values['content'])) {
            $this->setContent($values['content']);
        }
        if (isset($values['title'])) {
            $this->setTitle($values['title']);
        }
        if (isset($values['image'])) {
            $this->setImage($values['image']);
        }
        if (isset($values['link'])) {
            $this->setLink($values['link']);
        }
        if (isset($values['file'])) {
            $this->setFile($values['file']);
        }
        if (isset($values['new_tab'])) {
            $this->setNewTab($values['new_tab']);
        }
    }
}

templates/website/page/_crx-genetics-usp.twig
<div class="usps page-usps">
    <div class="usp-list">
        <div class="usp">
            <div class="image"><img src="{{ asset('uploads/' ~ blocks.11.image) }}"></div>
            <div class="text">
                <h3>{{ blocks.11.title }}</h3>
                <p>{{ blocks.11.subtitle }} </p>
            </div>
        </div>
        <div class="usp">
            <div class="image"><img src="{{ asset('uploads/' ~ blocks.12.image) }}"></div>
            <div class="text">
                <h3>{{ blocks.12.title }}</h3>
                <p>{{ blocks.12.subtitle }} </p>
            </div>
        </div>
        <div class="usp">
            <div class="image"><img src="{{ asset('uploads/' ~ blocks.13.image) }}"></div>
            <div class="text">
                <h3>{{ blocks.13.title }}</h3>
                <p>{{ blocks.13.subtitle }} </p>
            </div>
        </div>
        <div class="usp">
            <div class="image"><img src="{{ asset('uploads/' ~ blocks.14.image) }}"></div>
            <div class="text">
                <h3>{{ blocks.14.title }}</h3>
                <p>{{ blocks.14.subtitle }} </p>
            </div>
        </div>
    </div>
    <div class="clear"></div>
</div>

templates/website/page/_how-it-works-usp.twig
<div class="usps page-usps">
    <div class="usp-list">
        <div class="usp">
            <div class="image"><img src="{{ asset('uploads/' ~ blocks.7.image) }}"></div>
            <div class="text">
                <h3>{{ blocks.7.title }}</h3>
                <p>{{ blocks.7.subtitle }} </p>
            </div>
        </div>
        <div class="usp">
            <div class="image"><img src="{{ asset('uploads/' ~ blocks.8.image) }}"></div>
            <div class="text">
                <h3>{{ blocks.8.title }}</h3>
                <p>{{ blocks.8.subtitle }} </p>
            </div>
        </div>
        <div class="usp">
            <div class="image"><img src="{{ asset('uploads/' ~ blocks.9.image) }}"></div>
            <div class="text">
                <h3>{{ blocks.9.title }}</h3>
                <p>{{ blocks.9.subtitle }} </p>
            </div>
        </div>
        <div class="usp">
            <div class="image"><img src="{{ asset('uploads/' ~ blocks.10.image) }}"></div>
            <div class="text">
                <h3>{{ blocks.10.title }}</h3>
                <p>{{ blocks.10.subtitle }} </p>
            </div>
        </div>
    </div>
    <div class="clear"></div>
</div>

templates/website/page/_partners.twig
<div class="items">
    {% for partner in partners %}
        <div class="item-block">
            <div class="left">
                <a href="{{ partner.link }}"{% if partner.newTab %} target="_blank"{% endif %}>
                    <img class="item-image" src="{{ asset('uploads/' ~ partner.image) }}">
                </a>
            </div>
            <div class="right">
                <div class="item-text-position">
                    <a href="{{ partner.link }}"{% if partner.newTab %} target="_blank"{% endif %}><h2>{{ partner.name }}</h2></a>
                    <div class="item-text">{{ partner.content|raw }}</div>
                </div>
            </div>
            <div class="clear">&nbsp;</div>
        </div>
    {% endfor %}
</div>

templates/website/page/_xperts.twig
<div class="items">
    {% for x in xperts %}
        <div class="expert-block">
            <div class="left">
                <img class="item-image" src="{{ asset('uploads/' ~ x.image) }}">
            </div>
            <div class="right">
                <div class="item-text-position">
                    <h2>{{ x.name }}</h2>
                    <div class="item-text">{{ x.content|raw }}</div>
                </div>
            </div>
            <div class="clear">&nbsp;</div>
        </div>
    {% endfor %}
</div>

templates/website/page/page-view.twig
{% extends 'website/base.html.twig' %}

{% block title %}{{ page.title }}{% endblock %}

{% block body %}
    {% if page.header %}
        <div class="page-header" style="background-image: url('{{ asset('uploads/' ~ page.header) }}')">
            <div class="text-position">
                <div class="image-opacity-bar">
                    <h1 class="{{ page.slug }}">{{ page.title }}</h1>
                </div>
            </div>
        </div>
    {% endif %}

    {% if page.id == 7 %}
        {% include 'website/page/_how-it-works-usp.twig' %}
    {% endif %}

    {% if page.id == 3 %}
        {% include 'website/page/_crx-genetics-usp.twig' %}
    {% endif %}

    <div class="page-content">
        {% if not page.header %}
            <h1 class="no-header">{{ page.title }}</h1>
        {% endif %}
        {{ page.content|raw }}

        {% if page.id == 4 %}
            {% include 'website/page/_xperts.twig' %}
        {% endif %}

        {% if page.id == 6 %}
            {% include 'website/page/_partners.twig' %}
        {% endif %}
    </div>

    {% if page.footer %}
        <div class="page-footer" style="background-image: url('{{ asset('uploads/' ~ page.footer) }}')">
            {% if page.callToAction %}
                <div class="cta-position">

                </div>
                <a href="{{ page.callToActionLink }}" target="_blank">
                    <img class="call-to-action" src="{{ asset('uploads/' ~ page.callToAction) }}">
                </a>
            {% endif %}
        </div>
    {% endif %}
{% endblock %}