src/Entity/Product.php
<?php


namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class Product
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="decimal", scale=2)
     */
    private $price;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $ebook;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $video;

    /**
     * @ORM\Column(type="boolean")
     */
    private $has_genblueprint = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_clothing = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $deleted = false;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription($description)
    {
        $this->description = $description;
    }

    public function getPrice()
    {
        return $this->price;
    }

    public function setPrice($price)
    {
        $this->price = $price;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;
    }

    public function getEbook()
    {
        return $this->ebook;
    }

    public function setEbook($ebook)
    {
        $this->ebook = $ebook;
    }

    public function getVideo()
    {
        return $this->video;
    }

    public function setVideo($video)
    {
        $this->video = $video;
    }

    public function getHasGenblueprint()
    {
        return $this->has_genblueprint;
    }

    public function setHasGenblueprint($has_genblueprint)
    {
        $this->has_genblueprint = $has_genblueprint;
    }

    public function getIsClothing()
    {
        return $this->is_clothing;
    }

    public function setIsClothing($is_clothing)
    {
        $this->is_clothing = $is_clothing;
    }

    public function getDeleted()
    {
        return $this->deleted;
    }

    public function setDeleted($deleted)
    {
        $this->deleted = $deleted;
    }

    public function delete()
    {
        $this->deleted = true;
    }
}

src/Controller/Shop/CartController.php
<?php


namespace App\Controller\Shop;


use App\Controller\BaseController;
use App\Entity\Account;
use App\Entity\Order;
use App\Entity\OrderLine;
use App\Entity\Product;
use App\Service\Hostnames;
use App\Service\Localization;
use App\Service\ShoppingCart;
use Symfony\Component\HttpFoundation\Request;

class CartController extends BaseController
{
    public function cart(Request $request, Localization $localization, ShoppingCart $cart, Hostnames $host)
    {
        $this->checkLoggedInForShop($localization);

        if ($request->isMethod('post')) {
            if ($cart->getTotalPrice() < 0.01) {
                $this->addFlash('error', $localization->translate('Minimum order price is 1 cent'));
                return $localization->redirectToLocalizedRoute('account_shop_cart');
            }

            $order = $this->createNewOrder($cart);

            $mollie = new \Mollie_API_Client();
            $mollie->setApiKey($this->getParameter('mollie_api_key'));
            $payment = $mollie->payments->create([
                "amount"      => $cart->getTotalPrice(),
                "description" => $localization->translate('NEOBODIES order'),
                "redirectUrl" => $host->getWebsiteUrl() . $localization->getLocalizedRoute('account_shop_order_placed'),
                "webhookUrl"  => $host->getWebsiteUrl() . $localization->getLocalizedRoute('mollie_webhook'),
            ]);

            $order->setPaymentProviderId($payment->id);
            $order->setStatus('processing-payment');
            $this->save($order);
            $cart->clearCart();

            header("Location: " . $payment->getPaymentUrl());
            exit;
        }

        return $this->render(
            'website/shop/cart.twig',
            [
                'cart' => $cart->getCart(),
            ]
        );
    }

    public function clear(Localization $localization, ShoppingCart $cart)
    {
        $this->checkLoggedInForShop($localization);

        try {
            $cart->clearCart();
            $this->addFlash('success', $localization->translate('Cleared your shopping cart'));
                return $localization->redirectToLocalizedRoute('account_shop');
        } catch (\Exception $e) {
            $this->addFlash('error', $localization->translate('Could not clear your shopping cart'));
            return $localization->redirectToLocalizedRoute('account_shop_cart');
        }
    }

    private function createNewOrder($cart)
    {
        $account = $this->getDoctrine()->getRepository(Account::class)->findOneBy(['user' => $this->getUser()->getId()]);

        $order = new Order();
        $order->setAccount($account);
        $order->setTotalPrice($cart->getTotalPrice());
        $this->save($order);

        foreach ($cart->getCartItems() as $item) {
            $product = $this->getDoctrine()->getRepository(Product::class)->find($item['product']->getId());
            $orderLine = new OrderLine($order, $product, $item['price'], $item['amount'], $item['size'], $item['color']);
            $this->save($orderLine);
        }

        return $order;
    }
}

src/Controller/Shop/MollieController.php
<?php


namespace App\Controller\Shop;


use App\Controller\BaseController;
use App\Entity\Order;
use App\Service\Localization;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;

class MollieController extends BaseController
{
    public function webhook(Request $request, \Swift_Mailer $mailer, Localization $localization)
    {
        $mollie = new \Mollie_API_Client();
        $mollie->setApiKey($this->getParameter('mollie_api_key'));

        if (empty($request->request->get('id'))) {
            throw new HttpException(500, "That is not what we expect");
        }

        $payment = $mollie->payments->get($request->request->get('id'));
        if (!$payment) {
            throw new HttpException(404, "The ID Mollie gave is not known by Mollie (??)");
        }

        $order = $this->getDoctrine()->getRepository(Order::class)->findOneBy(['payment_provider_id' => $payment->id]);
        if (!$order) {
            throw new HttpException(404, "The Mollie ID is not known by us");
        }

        if ($payment->isPaid()) {
            $order->setStatus('paid');
            $order->setPaymentMethod($payment->method);
            try {
                $this->sendNewOrderEmail($mailer, $localization, $order);
            } catch (\Exception $e) {
                // Oh well
            }
        } elseif (! $payment->isOpen()) {
            $order->setStatus('aborted');
        }

        $this->save($order);

        return new Response();
    }

    protected function sendNewOrderEmail(\Swift_Mailer $mailer, Localization $localization, Order $order)
    {
        $account = $order->getAccount();
        $message = (new \Swift_Message($localization->translate('New order')))
        ->setFrom($account->getUser()->getEmail())
        ->setTo('info@neobodies.nl')
        ->setBody(
            $this->renderView(
                'email/new-order.twig',
                [
                    'order' => $order,
                ]
            ),
            'text/html'
        );

        $mailer->send($message);
    }
}

src/Controller/Shop/ShopController.php
<?php


namespace App\Controller\Shop;


use App\Controller\BaseController;
use App\Entity\Product;
use App\Service\Localization;
use App\Service\ShoppingCart;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\HttpException;

class ShopController extends BaseController
{
    public function shop(Localization $localization)
    {
        $this->checkLoggedInForShop($localization);

        $products = $this->getDoctrine()->getRepository(Product::class)->findBy([
            'deleted' => false,
        ]);

        return $this->render(
            'website/shop/products.twig',
            [
                'products' => $products,
            ]
        );
    }

    public function product($id, Request $request, Localization $localization, ShoppingCart $cart)
    {
        $this->checkLoggedInForShop($localization);

        $product = $this->getDoctrine()->getRepository(Product::class)->find($id);
        if (empty($product)) {
            throw new HttpException(404, $localization->translate('Could not find requested product'));
        }

        if ($request->isMethod('post')) {
            $amount = $request->request->get('amount') ? $request->request->get('amount') : 1;
            $size = $request->request->get('size') ? $request->request->get('size') : "";
            $cart->addToCart($product, $amount, $size);
            return $localization->redirectToLocalizedRoute('account_shop_cart');
        }

        return $this->render(
            'website/shop/product.twig',
            [
                'product' => $product,
            ]
        );
    }

    public function orderPlaced()
    {
        return $this->render(
            'website/shop/order-placed.twig',
            [

            ]
        );
    }

}

templates/website/shop/cart.twig
{% extends 'website/base.html.twig' %}

{% block title %}{% trans %}Shopping cart{% endtrans %}{% endblock %}

{% block body %}
<div class="page-content">
    <div class="shoppingcart">
        <div class="top-bar">
            <a href="{{ getLocalizedRoute('clear_cart') }}" class="button-small back-button">{% trans %}Clear cart{% endtrans %}</a>
            <a href="{{ getLocalizedRoute('account_shop') }}" class="button-small back-button">{% trans %}Continue shopping{% endtrans %}</a>
        </div>
        <h1>{% trans %}Shopping cart{% endtrans %}</h1>
        <div class="items">
            {% for item in cart.items %}
                <div class="item">
                    <a href="{{ getLocalizedRoute('account_shop_product', {id: item.product_id}) }}">{{ item.product.title }}</a>
                    x{{ item.amount }}
                    {% if item.color %} | {{ item.color|capitalize }}{% endif %}
                    {% if item.size %} | {{ item.size|capitalize }}{% endif %}
                    <span class="right">&euro;{{ item.price|number_format(2) }}</span>
                    <div class="clear">&nbsp;</div>
                </div>
            {% endfor %}
        </div>
        <div class="summary">
            <h2>{% trans %}Total price{% endtrans %}: &euro;{{ cart.total_price|number_format(2) }}</h2>

            <form method="post">
                <button type="submit" class="button-large">{% trans %}Confirm{% endtrans %}</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/website/shop/order-placed.twig
{% extends 'website/base.html.twig' %}

{% block title %}{% trans %}Thank you{% endtrans %}{% endblock %}

{% block body %}
    <div class="page-content">
        <div class="order-placed">
            <h1>{% trans %}Thank you!{% endtrans %}</h1>
            <p>
                {% trans %}Your order has been received.{% endtrans %}<br>
                {% trans %}The order will be processed as soon as possible.{% endtrans %}
            </p>
        </div>
    </div>
{% endblock %}

templates/website/shop/product.twig
{% extends 'website/base.html.twig' %}

{% block title %}{% trans %}Shop{% endtrans %}{% endblock %}

{% block body %}
    <div class="page-content">
        <div class="product">
            <div class="top-bar">
                <a href="{{ getLocalizedRoute('account_shop') }}" class="button-small back-button">{% trans %}Back to overview{% endtrans %}</a>
                <a href="{{ getLocalizedRoute('account_shop_cart') }}" class="button-small back-button">{% trans %}Cart{% endtrans %}</a>
            </div>
            <div class="left">
                <img src="{{ asset('uploads/' ~ product.image ) }}">
            </div>
            <div class="right">
                <div class="cart">
                    <h1>{{ product.title }}</h1>
                    <p class="price">&euro;{{ product.price|number_format(2) }}</p>

                    {% if not product.deleted %}
                        <form method="post">
                            {% if product.isClothing %}
                                <div class="product-field">
                                    <select name="size">
                                        <option value="">{% trans %}Pick a size{% endtrans %}</option>
                                        <option value="xs">XS</option>
                                        <option value="s">S</option>
                                        <option value="m">M</option>
                                        <option value="l">L</option>
                                        <option value="xl">XL</option>
                                    </select>
                                </div>
                            {% endif %}
                            <div class="product-field">
                                <label for="quantity">{% trans %}Quantity{% endtrans %}</label>
                                <input type="number" name="amount" value="1">
                                <button type="submit" class="button-large">{% trans %}Add to cart{% endtrans %}</button>
                            </div>
                            <div class="clear">&nbsp;</div>
                        </form>
                    {% endif %}
                </div>
                <div class="info">
                    <h2>{% trans %}Product description{% endtrans %}</h2>
                    <p class="description">{{ product.description|raw }}</p>
                </div>
            </div>
            <div class="clear">&nbsp;</div>
        </div>
    </div>
{% endblock %}

templates/website/shop/products.twig
{% extends 'website/base.html.twig' %}

{% block title %}{% trans %}Shop{% endtrans %}{% endblock %}

{% block body %}
    <div class="account-content">
        <div class="shop">
            <div class="top-bar">
                <a href="{{ getLocalizedRoute('account') }}" class="button-small back-button">{% trans %}Back to account{% endtrans %}</a>
                <a href="{{ getLocalizedRoute('account_shop_cart') }}" class="button-small back-button">{% trans %}Cart{% endtrans %}</a>
            </div>
            <h1>{% trans %}Shop{% endtrans %}</h1>
            <div class="products">
                {% for product in products %}
                    <div class="product-wrapper">
                        <a href="{{ getLocalizedRoute('account_shop_product', {id: product.id}) }}" class="item">
                            <div class="product">
                                <div class="image">
                                    <img src="{{ asset('uploads/' ~ product.image ) }}">
                                </div>
                                <div class="info">
                                    <p class="title">{{ product.title }}</p>
                                    <p class="price">&euro;{{ product.price|number_format(2) }}</p>
                                </div>
                            </div>
                        </a>
                    </div>
                    {% if loop.index is divisible by(2) %}
                        <div class="clear by-two">&nbsp;</div>
                    {% endif %}
                    {% if loop.index is divisible by(3) %}
                        <div class="clear by-three">&nbsp;</div>
                    {% endif %}
                {% endfor %}
                <div class="clear">&nbsp;</div>
            </div>
            <div class="clear">&nbsp;</div>
        </div>
    </div>
{% endblock %}